GET http://localhost:8082/users

###

# POST http://localhost:8082/api/users/
# Content-Type: application/json

# {
#     "username": "ssong",
#     "password": "password",
#     "email": "ssong@gmail.com"
# }

###

POST http://localhost:8082/users/login
Content-Type: application/json

{
    "username": "henryshih",
    "password": "henryshih"
}

###




GET http://localhost:8082/users
Content-Type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMSIsInVzZXJJZCI6IjYzNjE2MWRlYjNkOGNhNjMzM2Q5Y2RjNSIsInJvbGUiOiJST0xFLkFETUlOIiwiaWF0IjoxNjY3MzMyMzgzLCJleHAiOjE2Njc0MTg3ODN9.j_PuwW0vdRoolrIGDl3prUBY38Jrp1zVG-uHOMmPy5k


###

GET http://localhost:8082/users/admin
Content-Type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMSIsInVzZXJJZCI6IjYzNjE2MWRlYjNkOGNhNjMzM2Q5Y2RjNSIsInJvbGUiOiJST0xFLkFETUlOIiwiaWF0IjoxNjY3MzMyMzgzLCJleHAiOjE2Njc0MTg3ODN9.j_PuwW0vdRoolrIGDl3prUBY38Jrp1zVG-uHOMmPy5k


###

GET http://localhost:8082/users/admin
Content-Type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbnJ5c2hpaCIsInVzZXJJZCI6IjYzNjAxZjkwYTUyMzg0MjJlNzViZDg1MCIsInJvbGUiOiJST0xFLkJBU0lDIiwiaWF0IjoxNjY3MzMyNTc0LCJleHAiOjE2Njc0MTg5NzR9.-N9B9ut0X9LpcS5Uq49jmrraKAdTBoNMSu9-qubqeb4
