GET http://localhost:8082/api/users/

###

# POST http://localhost:8082/api/users/
# Content-Type: application/json

# {
#     "username": "ssong",
#     "password": "password",
#     "email": "ssong@gmail.com"
# }

###
